server:
  port: 8181
management:
  security:
    enabled: false
spring:
  application:
    name: bootstrap-demo
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/rjhy?characterEncoding=utf8&useSSL=true
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #cache:
  #  ehcache:
  #    config: classpath:/ehcache-shiro.xml
  #redis:
  #  host: localhost
  #  port: 6379
  #  password: null
  #  timeout: 20
druid:
  pool:
    initialSize: 10
    maxActive: 100
    minIdle: 10
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.rjhy.cloud.entity
#  global-config:
#    id-type: 3
#    field-strategy: 2
#    auto-set-db-type: true
#    db-column-underline: true
#    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#logging:     #此处配置后，logback-spring.xml 将无效
#    file: log.log
#    level: 
#      com.rjhy.cloud: debug